title: Calacirya
description: Sí vanwa ná, Rómello vanwa, Valimar!
repository: calacirya/calacirya.github.io

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-github-metadata

sass:
  style: compressed

theme: jekyll-theme-cayman

# If you want a starred project on display, add it's name below.
# Please note that this method draws the from GitHub Metadata's
#   public_repositories to show appropriate data.
star_project: Hearth

menus:
  - link: "/posts"
    text: "Blog"
