title: Calacirya
description: Sí vanwa ná, Rómello vanwa, Valimar!
github_username:  Calacirya

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-sitemap
  - jekyll-feed

theme: jekyll-theme-cayman

#menus:
#  - link: "/coc"
#    text: "Code of Conduct"
