title: Calacirya
description: Sí vanwa ná, Rómello vanwa, Valimar!
home: https://github.com/calacirya/

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-sitemap
  - jekyll-feed

theme: jekyll-theme-cayman

#menus:
#  - link: "/coc"
#    text: "Code of Conduct"

#projects:
#  - repo: project-name
#    name: Project Name
